# Generated by Django 5.1.1 on 2025-04-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
