# Generated by Django 5.1.1 on 2025-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_alter_otpcode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
