# Generated by Django 5.1.1 on 2024-10-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='alternative_image', upload_to='products_images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='alternative_image', upload_to='products_cover_image/'),
        ),
    ]
