# Generated by Django 5.1.1 on 2024-10-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
    ]
