# Generated by Django 5.1.1 on 2024-10-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_attribute_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name', 'category')},
        ),
    ]
