# Generated by Django 5.1.1 on 2025-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_path',
            field=models.TextField(blank=True),
        ),
    ]
