# Generated by Django 5.1.1 on 2025-01-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_category_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_path',
        ),
    ]
