# Generated by Django 5.1.1 on 2025-01-25 16:02

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_tags_category_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
