# Generated by Django 5.1.1 on 2025-01-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_category_tags_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
