# Generated by Django 5.1.1 on 2025-01-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
