# Generated by Django 5.1.1 on 2025-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
    ]
